### ISSUE TITLE
'libCore.a' file does not exist.

### ISSUE THREAD

**Issue by K-UseBy** [opendarkeden/server#11] opened 2021-06-28 14:15 UTC
![issue](https://user-images.githubusercontent.com/49011864/123651688-a74c6e80-d866-11eb-8bd9-d1fa6366390a.PNG)
When I enter the 'make' command to build, it says that the 'libCore.a' file does not exist.
I tried to find it. but it's really not exist in your project what I cloned.
How can I solve it?
Can I receive that file?

**Comment by tiancaiamao** [comment] 2021-06-29 01:25
@K-UseBy  Did you try the latest master?  It should have been fixed in https://github.com/opendarkeden/server/issues/6
This is caused by the `$project_home/lib` directory does exist.
You can manually create one, and then call `make` again

```
mkdir lib
```

**Comment by K-UseBy** [comment] 2021-06-29 13:08
> @K-UseBy Did you try the latest master? It should have been fixed in #6
> This is caused by the `$project_home/lib` directory does exist.
> You can manually create one, and then call `make` again
> 
> ```
> mkdir lib
> ```
it worked for me :)

**Closed** 2021-06-29 13:08 UTC
