### ISSUE TITLE
[BUG] Summoner Pet's.

### ISSUE THREAD

**Issue by xDezossAx** [opendarkeden/server#36] opened 2021-09-01 00:36 UTC
Hi @tiancaiamao , I found that when using Hourglass, transforming with the sylph from ousters, or any consumable item in the inventory, megaphone, summon pet (wolfdog) nothing happened, it locked the storage, and did not return any error in the logs, so I applied that fix you made in the CGSkillToInventory.cpp and .h files to fix the transformation of werwolf, bat and wolf, the same correction in the CGUseItemFromInventory.cpp and .h files, and the ouster's Hourglass, megaphone and sylph worked, however the pets, I summon them, apparently you increase my stat if they have attributes, they gain experience with the summoned time, but it doesn't show the look, in this case the summoned creature, and it takes items from the monsters. I believe that in the case of the pet, there is another file to be corrected, can you help me? your eyes are more trained than mine. Follow in the return image on the server:

![image](https://user-images.githubusercontent.com/51914495/131592744-ce2e0573-6ede-4184-83a6-226ddd14280d.png)

**Comment by xDezossAx** [comment] 2021-09-01 02:15
When I use the client in debug mode in another binary I have here, it summons normally, and returns the following log:

LOG CLIENT OK:
_[UI] Execute OK
ModifyInfo[ShortCount:0,ShortListSet(),LongCount:0,LongListSet()]
AMo
LD
AM_ok
[PacketExecute OK1]
[PacketExecute OK2]
GCBloodBibleSignInfo()
[PacketExecute OK1]
[PacketExecute OK2]
GCPetInfo()
MZone::AddFakeCreature id = 1696684
EGT-Generate. ai=1696120, target=0x19E294
et=0x19E174, targetID=1696404, targetPhase=1
et=0x19E174, targetID=1696404, targetPhase2=1
Generate before. id=1696124
CreateAttachEffect. type=1695724, delayf=1695944
NewEffect : Type=1695716, Light=1695944, (71, 3981312)
[MEffect]SetLink: ai=1695848, effectTarget=NULL
Generate true
et=0x19E174, targetID=1696404, targetPhase3=1696152
Check Result
NO Result
delete EffectTarget
delete EffectTarget. id=1695932
del res
del ok
EGT-Generate OK. ai=1696120, target=0x19E294
[ExecuteActionInfoFromMainNode] ai=1696420
[PacketExecute OK1]
[PacketExecute OK2]
GCUseOK(ModifyInfo[ShortCount:0,ShortListSet(),LongCount:0,LongListSet()])
Set Item Check Buffer to NULL_

Log Server OK: 

![image](https://user-images.githubusercontent.com/51914495/131600739-2ff3b63e-afcc-42e5-8b08-2337b332b18e.png)

**Comment by xDezossAx** [comment] 2021-09-01 02:35
LOG CLIENT ERROR:

_[UI] Execute OK
ModifyInfo[ShortCount:1,ShortListSet(TOHIT:2271,),LongCount:0,LongListSet()]
AMo
LD
AM_ok
[PacketExecute OK1]
[PacketExecute OK2]
GCBloodBibleSignInfo()
[PacketExecute OK1]
[PacketExecute OK2]
GCPetInfo()
[GCPetInfoHandler] ÆêÀ» ¾ø¾Ù·Á°í º¸´Ï±î ÁÖÀÎ³ðÀÌ ÆêÀÌ ¾ø³× ±×·Á
[PacketExecute OK1]
[PacketExecute OK2]
GCUseOK(ModifyInfo[ShortCount:0,ShortListSet(),LongCount:0,LongListSet()])
Set Item Check Buffer to NULL_

something related to gcpetInfoHandler.cpp ?

**Comment by tiancaiamao** [comment] 2021-09-04 12:22
I'm trying to reproduce it and ... er ... I find some problem in this database.

**Comment by xDezossAx** [comment] 2021-09-04 20:53
I believe there is an error related to the objectID, so much so that you put the pet in the pet storage
(CGDepositPet)
and withdraw normally. But when it relogs and comes back to withdraw it loses the ObjectID, it stays zeroed.

I'm trying to check the CGWithdrawPet file.

I will try to simulate with firecracker because it is an item that is in storage, and when it clicks it generates a sprite, I return to give feedback :)

**Comment by tiancaiamao** [comment] 2021-09-05 07:18
... I can't find any dogs in the map ... that's weird ... do you know the reason? @xDezossAx

**Comment by xDezossAx** [comment] 2021-09-05 11:15
I don't either, in the image above I used the client-master you provided, but with other server files ie the client is ok, but some error in the server files, with the server files here, the client returns the following error:

When will you summon the pet:
[GCPetInfoHandler] ÆêÀ» ¾ø¾Ù·Á°í º¸´Ï±î ÁÖÀÎ³ðÀÌ ÆêÀÌ ¾ø³× ±×·Á

when will you store the pet:
[GCPetInfoHandler] ÆêÀ» ¾ø¾Ù·Á°í º¸´Ï±î ÁÖÀÎ³ðÀº ÆêÀÌ ÀÖ´Âµ¥ ¸·»ó ÆêÀÌ ¾ø³× ±×·Á 

Looking at the client's PacketFunction.cpp, it is bringing the objectID of the server NULL, so the first error, and to save it doesn't find the FakeCreature, as it couldn't get a reference to summon with the objectID, it didn't have to save. Here is an excerpt from PacktFunction.cpp:

`			if(pCreature->GetPetID() != OBJECTID_NULL) << **if it was different from null he would create the creature in the act of summoning.**
			{
				MFakeCreature *pFakeCreature = (MFakeCreature *)g_pZone->GetFakeCreature(pCreature->GetPetID());

				if(pCreature != g_pPlayer)
				{
					if(gC_vs_ui.GetCurrentOtherInfoName() != NULL &&
						strcmp(pCreature->GetName(), gC_vs_ui.GetCurrentOtherInfoName()) == 0 )
					{
						gC_vs_ui.SetOtherPetInfo(NULL);
					}
				}

				if(pFakeCreature != NULL)  << **if it was different from null it would guard the creature.**
				{
					g_pZone->RemoveFakeCreature(pCreature->GetPetID());
				}
				else
				{
					DEBUG_ADD("[GCPetInfoHandler] ÆêÀ» ¾ø¾Ù·Á°í º¸´Ï±î ÁÖÀÎ³ðÀº ÆêÀÌ ÀÖ´Âµ¥ ¸·»ó ÆêÀÌ ¾ø³× ±×·Á");
				}
			}
			else
			{
				DEBUG_ADD("[GCPetInfoHandler] ÆêÀ» ¾ø¾Ù·Á°í º¸´Ï±î ÁÖÀÎ³ðÀÌ ÆêÀÌ ¾ø³× ±×·Á");
			}`
But on the server/database, he's summoned, and gaining exp, increases the character's status, just doesn't have animation, doesn't attack, doesn't drop items/heads, because the creature doesn't exist in the client.

**Comment by tiancaiamao** [comment] 2021-09-05 12:36
Let me try some GM command to generate a pet for testing ...

**Comment by tiancaiamao** [comment] 2021-09-05 14:08
I find there are three problems.

- The first one is using consumable item cause the client panic, caused by `CGUseItemFromInventory.cpp`.
- The second one, the server empty pet info the the client, this cause summoner's pet do not show.
- The final one, maybe related the to database data, I can't find any wild dog in the zone, I test another database and the wild dog show up...

The first one is fixed in https://github.com/opendarkeden/server/pull/41, thanks for your report @xDezossAx

**Comment by xDezossAx** [comment] 2021-09-05 14:21
for nothing friend o/ @tiancaiamao 

> I find there are three problems.
> 
> * The first one is using consumable item cause the client panic, caused by `CGUseItemFromInventory.cpp`.
> * The second one, the server empty pet info the the client, this cause summoner's pet do not show.
> * The final one, maybe related the to database data, I can't find any wild dog in the zone, I test another database and 
the wild dog show up...

I fully agree with both situations, with a problem in the bank I think it is not, the problem is to send the empty objectID to the client, so much so that when you put the pet in the stash (pet bank) and relog it, you cannot remove it, because loses the ObjectID reference too.

about the pet, that's what I identified too, translating what happens, when I summon, it returns:

Archive Client/PacketFunction.cpp Line: 5236: _I searched for an item to attach a pet, but no item (1696812)_ < because pItem = NULL

and when I go to save the pet, it returns the following:

Archive Client/PacketFunction.cpp Line: 5006: When I tried to get rid of the pet, the owner didn't have a pet. < because if(pCreature->GetPetID() = OBJECTID_NULL)

**Closed** 2021-09-25 14:40 UTC

**Comment by tiancaiamao** [comment] 2021-09-25 14:41
Hi, @xDezossAx 
I've fixed the bug, you can pull the latest code and take another try.
The server doesn't correctly set the pet item object ID in the GCPetInfo packet cause this bug.

**Comment by xDezossAx** [comment] 2021-09-27 02:39
Thank you @tiancaiamao, u very best bro!! o/
